### PR TITLE
fix: handlers enabled when options.enabled=false

### LINKED ISSUE #181: Nodes are still draggable when options.enabled is false
**Describe the bug**

We're able to drag around a node that is connected when passing `enabled={false}` to the Craft provider.

To bypass this, we can ensure to not attach the drag handler when not enabled, but this should work regardless `<div ref => enabled && connect(drag(ref))>...</div>`

### PR DESCRIPTION
**Pull request by prevwong**
Fix #181

### CODE REVIEW

File: packages/core/src/events/Events.tsx [hunk 1]
```diff
@@ -52,17 +52,17 @@ export const Events: React.FC = ({ children }) => {
...
     if (!enabled) {
-      handlersRef.current.disable();
+      handlers.disable();
       return;
     }
 
-    handlersRef.current.enable();
-  }, [enabled]);
+    handlers.enable();
+  }, [enabled, handlers]);
```
Comment (ankri) [inline packages/core/src/events/Events.tsx:65]: I think it would be enough to add `handlersRef.current` to the dependency array:

```tsx
  // Disable/Enable handlers when the enabled state is toggled
  useEffect(() => {
    if (!handlersRef.current) {
      return;
    }

    if (!enabled) {
      handlersRef.current.disable();
      return;
    }

    handlersRef.current.enable();
  }, [enabled, handlersRef.current]);
```

Comment (ankri) [reply packages/core/src/events/Events.tsx:65]: My tests seem to confirm, that it is enough to add `handlersRef.current` to the dependency array

Comment (prevwong) [reply packages/core/src/events/Events.tsx:65]: Is it good practice though? I don't think we should depend on ref values as dependencies? https://github.com/facebook/react/issues/16121

Comment (ankri) [reply packages/core/src/events/Events.tsx:65]: Wouldn't that be the case for `useMemo` then?

```tsx
  const memoizedStore = React.useMemo(() => store, [store]);
  const memoizedHandlers = React.useMemo(() => handlers, [handlers]);

  // Generate new handlers whenever the editor deserializes a new state
  useEffect(() => {
    // TODO: Remove this when we refactor the EditorState
    actions.history
      .ignore()
      .setState((state) => (state.handlers = handlersFactory(memoizedStore)));

    return () => {
      if (!memoizedHandlers) {
        return;
      }

      memoizedHandlers.cleanup();
    };
  }, [actions, handlersFactory, hydrationTimestamp]);

  // Disable/Enable handlers when the enabled state is toggled
  useEffect(() => {
    if (!memoizedHandlers) {
      return;
    }

    if (!enabled) {
      memoizedHandlers.disable();
      return;
    }

    memoizedHandlers.enable();
  }, [enabled, memoizedHandlers]);
```

But... why do we need to use `ref` or `memo` anyways? 🤔 

Since we do
```tsx
  const storeRef = useRef(store);
  storeRef.current = store;
  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;
```
and I cannot find a place where we would need to have access to "reffed" version of the store or handlers? Am I missing something? 🤔

Comment (prevwong) [reply packages/core/src/events/Events.tsx:65]: Yeah I need the ref values here: https://github.com/prevwong/craft.js/blob/e250f449841feb007c4e54448dbdc8b57d39bba0/packages/core/src/events/Events.tsx#L41-L49

If I use `memoizedStore` and `memoizedHandlers` like in your example - then I will need to add those as a dependency to that `useEffect` hook, but that will cause that hook to execute everytime `handlers` and `store` is updated.

Comment (ankri) [reply packages/core/src/events/Events.tsx:65]: Thanks. LGTM then 🙂 👍

**Comment by timc1** [comment]
@prevwong can we get a release with this? 💯

**Comment by prevwong** [comment]
@timc1 Done! Sorry about the delay; really gotta fix the CI for the next branch 😁

**Comment by timc1** [comment]
@prevwong this seems to still be the case when we have nodes like so:

```
<Element is={SomeComponent} canvas>
  <ChildBlock />
  <ChildBlock />
  <ChildBlock />
</Element>
```

wherein the `ChildBlock`s show the handlers when the editor is disabled 😞

**Comment by hugominas** [comment]
Same here, the latest working release seems to be 0.2.0-alpha.13 
I was thinking about creating a separate renderer like what was discussed in this issue https://github.com/prevwong/craft.js/issues/42

**Comment by timc1** [comment]
Got around this by placing the drag listener on a small drag handle, which itself is not rendered when the editor is disabled
