### PR TITLE
fix: sync <Editor /> props with state options

### LINKED ISSUE #149: Cannot update editor options
This assignment to the function argument does not make sense, as it will do nothing.
https://github.com/prevwong/craft.js/blob/75285b20fe7fc37390c5b3bfd7b43719b0d022f8/packages/core/src/editor/Editor.tsx#L31

I noticed this, because I tried to toggle enabled on the editor, however with no effect.

### PR DESCRIPTION
**Pull request by aroramayur**
Closes #149

 - Updates Editor's options as a side-effect.

### CODE REVIEW

**Review by prevwong — APPROVED** [review]
Thank you! 💯

File: packages/core/src/editor/Editor.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const Editor: React.FC<Partial<Options>> = ({
   useEffect(() => {
     if (context && options)
       context.actions.setOptions((editorOptions) => {
-        editorOptions = options;
+        Object.assign(editorOptions, options);
       });
   }, [context, options]);
```
Comment (prevwong) [inline packages/core/src/editor/Editor.tsx:33]: Actually, on a second look, there's more to this - the `options` object changes way too frequently, thus the `useEffect` hook will get triggered too frequently as well.

On top of my head, I can think of 2 options:
1. Use `lodash/isEqualWith` to compare the `options` prop with the previous `options`. But I'm not a fan of using deepEquals, so it would be great if we can avoid this.

2. Memoize the `options` object:
```tsx
export const Editor: React.FC<Partial<Options>> = ({
  children,
  onNodesChange,
  onRender,
  enabled,
  resolver,
  indicator,
  handlers,
}) => {
  const options = useMemo(
    () => ({
      ...
    }),
    [onNodesChange, onRender, enabled, resolver, indicator, handlers]
  );

  ...
});
```

**Review by prevwong — CHANGES_REQUESTED** [review]

**Review by prevwong — APPROVED** [review]
LGTM 💯

**Comment by akucinskii** [comment]
Hey, was this pr released?
